apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: d92wp2f9o-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: d92wp2f9o-go 
  name: d92wp2f9o-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: d92wp2f9o-go 
